name: Docker Copiler
on:
  push:
  schedule:
    - cron: 0 0 * * 5
env:
 IMAGE1: sirherobrine23/openwrtbuild-ci

jobs:
  Docker-Image-Build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@master
      
     - name: Login
       run: 
        docker login -u "${{ secrets.USER }}" -p "${{ secrets.PASSWORD }}"

     - name: Build
       run: |
         HASS=$(echo "$IMAGE1:$(git rev-parse HEAD)")
         LAST=$(echo "$IMAGE1:latest")
         docker build -t "$LAST" .
         docker push "$LAST"
         docker build -t "$HASS" .
         docker push "$HASS"
